import { useCallback, useEffect, useRef, useState } from "react";

type PagefindResult = {
  id: string;
  data: () => Promise<{ url: string; excerpt: string; meta: { title?: string } }>;
};

type Pagefind = {
  init: () => Promise<void>;
  search: (term: string) => Promise<{ results: PagefindResult[] }>;
};

type Hit = { id: string; url: string; title: string; excerpt: string };

type Props = {
  strings: {
    open: string;
    placeholder: string;
    hint: string;
    empty: string;
    unavailable: string;
    results: string;
  };
};

const MAX_HITS = 8;

/** Pagefind is generated by `npm run build`, so it only exists in the built site. */
const loadPagefind = async (): Promise<Pagefind> => {
  const pagefind = (await import(/* @vite-ignore */ `${import.meta.env.BASE_URL}pagefind/pagefind.js`)) as Pagefind;
  await pagefind.init();
  return pagefind;
};

export default function SearchModal({ strings }: Props) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [hits, setHits] = useState<Hit[]>([]);
  const [active, setActive] = useState(0);
  const [failed, setFailed] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const pagefind = useRef<Pagefind | null>(null);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
        event.preventDefault();
        setOpen((value) => !value);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, []);

  useEffect(() => {
    if (!open) return;
    input.current?.focus();
    document.body.style.overflow = "hidden";
    if (!pagefind.current) {
      loadPagefind()
        .then((instance) => {
          pagefind.current = instance;
        })
        .catch(() => setFailed(true));
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [open]);

  useEffect(() => {
    const term = query.trim();
    if (!term) {
      setHits([]);
      return;
    }
    let cancelled = false;
    const timer = setTimeout(async () => {
      if (!pagefind.current) return;
      const search = await pagefind.current.search(term);
      const data = await Promise.all(search.results.slice(0, MAX_HITS).map((hit) => hit.data()));
      if (cancelled) return;
      setHits(
        data.map((entry, index) => ({
          id: search.results[index]!.id,
          url: entry.url,
          title: entry.meta.title ?? entry.url,
          excerpt: entry.excerpt,
        })),
      );
      setActive(0);
    }, 160);
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [query]);

  const onKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === "Escape") setOpen(false);
      if (event.key === "ArrowDown") {
        event.preventDefault();
        setActive((index) => (hits.length ? (index + 1) % hits.length : 0));
      }
      if (event.key === "ArrowUp") {
        event.preventDefault();
        setActive((index) => (hits.length ? (index - 1 + hits.length) % hits.length : 0));
      }
      if (event.key === "Enter" && hits[active]) {
        window.location.href = hits[active]!.url;
      }
    },
    [hits, active],
  );

  return (
    <>
      <button
        type="button"
        aria-label={strings.open}
        onClick={() => setOpen(true)}
        className="flex cursor-pointer items-center gap-2 rounded border border-border px-2 py-1 text-muted transition-colors hover:border-accent-dim hover:text-accent"
      >
        <svg width="14" height="14" viewBox="0 0 16 16" aria-hidden="true">
          <circle cx="6.5" cy="6.5" r="4.5" fill="none" stroke="currentColor" strokeWidth="1.5" />
          <path d="M10 10l4 4" stroke="currentColor" strokeWidth="1.5" />
        </svg>
        <kbd className="hidden font-mono text-[10px] tracking-wider sm:inline">⌘K</kbd>
      </button>

      {open && (
        <div
          className="fixed inset-0 z-100 flex items-start justify-center bg-black/70 px-4 pt-[10vh]"
          role="presentation"
          onClick={(event) => {
            if (event.target === event.currentTarget) setOpen(false);
          }}
        >
          <div
            role="dialog"
            aria-modal="true"
            aria-label={strings.open}
            className="w-full max-w-2xl overflow-hidden rounded-lg border border-border bg-surface"
          >
            <div className="flex items-center gap-3 border-b border-border px-4 py-3">
              <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true" className="text-muted">
                <circle cx="6.5" cy="6.5" r="4.5" fill="none" stroke="currentColor" strokeWidth="1.5" />
                <path d="M10 10l4 4" stroke="currentColor" strokeWidth="1.5" />
              </svg>
              <input
                ref={input}
                type="search"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                onKeyDown={onKeyDown}
                placeholder={strings.placeholder}
                className="w-full bg-transparent text-fg outline-none placeholder:text-muted"
              />
              <kbd className="font-mono text-[10px] text-muted">ESC</kbd>
            </div>

            <div className="max-h-[60vh] overflow-y-auto">
              {failed && <p className="px-4 py-6 text-sm text-muted">{strings.unavailable}</p>}
              {!failed && !query.trim() && (
                <p className="px-4 py-6 text-sm text-muted">{strings.hint}</p>
              )}
              {!failed && query.trim() && hits.length === 0 && (
                <p className="px-4 py-6 text-sm text-muted">{strings.empty}</p>
              )}
              <ul>
                {hits.map((hit, index) => (
                  <li key={hit.id}>
                    <a
                      href={hit.url}
                      onMouseEnter={() => setActive(index)}
                      className={`block border-b border-border px-4 py-3 last:border-b-0 ${
                        index === active ? "bg-raised" : ""
                      }`}
                    >
                      <span className="block text-sm font-medium text-strong">{hit.title}</span>
                      <span
                        className="mt-1 block text-xs leading-relaxed text-muted [&_mark]:bg-transparent [&_mark]:text-accent"
                        dangerouslySetInnerHTML={{ __html: hit.excerpt }}
                      />
                    </a>
                  </li>
                ))}
              </ul>
              {hits.length > 0 && (
                <p className="px-4 py-2 font-mono text-[10px] text-muted">
                  {hits.length} {strings.results}
                </p>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
